feat: Add height parameter to limit the box height
NikolaiMe/textbox-for-pdfkit pull request #13
Opened 2024-10-16 13:28 UTC by b-alidra

This patch adds a `height` parameter to the `addTextbox` function.  
This height is used to limit the number of lines to write into the box.

2024-10-25 12:20 UTC, NikolaiMe commented
Hello @b-alidra,
thank you for your contribution. This is basically a usefull feature. Unfortunately your current implementation breaks the existing implementation.

When I run my example code the expected result is the following:
![image](https://github.com/user-attachments/assets/93ab8001-2201-4977-8015-6c1e4dbef52a)

But when I ran the example with your code. I got the following result:
![image](https://github.com/user-attachments/assets/9f76dac1-5e82-4c94-b127-24716dbad54b)

The reason for this, is, that you added the `height` parameter in the addTextbox function in front of the `style` parameter.

`addTextbox(text,` doc, posX, posY, width, height, style = {})`

--> Therefore every user would need to change all the code which is currently using the style parameter to 

`addTextbox("text",` doc, 10, 15, 50, null, style = {})`

(the `null` needs to be added everywhere)

--> This means it is not downwards compatible and everyone who would update to the new package version would need to adapt the existing code to keep the package working. This is not good practice and can easily avoided by adding new optional parameters only to the very end of a function call.

Feel free to correct your implementation and provide an updated version. But please make sure that before you do the pull request, that you at least ran the two functions `testMe()` and `testMePartTwo()`, which are both part of "./examples/testPDFGenerator.js". Please compare then the resulting pdfs (test.pdf and testPartTwo.pdf) with the pdfs which can  be found in the gitHub repository. 

The best would be if you could add another testRoutine (e.g. testMePartThree()) which then also includes your new feature.

Short info: To really check your own code (and not the implementation which is right now on npm) you need to change the first line of testPDFGenerator.js to `const addTextbox = require("../js/pdfTextbox");`

2024-10-25 12:24 UTC, NikolaiMe requested changes
See my detailed comment above :)

2024-10-25 12:24 UTC, NikolaiMe commented on README.md
> +  addTextbox(testTextArray, doc, 100, 100, 200, /*height*/null, {
Please remove the null to make it downward compatible

2024-10-25 12:24 UTC, NikolaiMe commented on README.md
> +addTextbox(textArray, doc, posX, posY, width, height, defaultStyle);
change position of height and defaultStyle to make it downward compatible

2024-10-25 12:24 UTC, NikolaiMe commented on README.md
> +- **height:** The maximum height of your Textbox (in PDF-points, optional)
Switch position of height and defaultStyle to make it downward compatible

2024-10-25 12:24 UTC, NikolaiMe commented on js/pdfTextbox.js
> +function addTextbox(text, doc, posX, posY, width, height, style = {}) {
Switch position of height and defaultStyle to make it downward compatible

2024-10-25 12:24 UTC, NikolaiMe commented on js/pdfTextbox.js
> +  drawTextLinesOnPDF(optimizedLines, width, height, posX, posY, textboxStyle, doc, baseline);
Move the height parameter to the very end of the function

2024-10-25 12:24 UTC, NikolaiMe commented on js/pdfTextbox.js
> +function drawTextLinesOnPDF(lines, width, height, posX, posY, defaultStyle, doc, baseline) {
Move the height parameter to the very end of the function

2024-10-25 15:28 UTC, b-alidra commented
Hi @NikolaiMe and thank you for your review.

I've put the `height` parameter right after the `width` one because I think it makes sense but you're right about the downwards compatibility.
I changed my implementation and followed your remarks.
I've added a new test routine and the three are giving correct results.

Thanks again for your time.

2024-10-26 09:03 UTC, NikolaiMe commented
Wonderful! Thanks for your work and contribution! I will merge your branch into main now

2024-10-26 09:03 UTC, merged

2025-03-11 07:43 UTC, jeremywillans commented
@b-alidra, is there any way this could be expanded to vertically justify the text in the text box? 
If I have one line, i would like it to be in the middle, not at the top?

im thinking perhaps calculate total height of provided lines, and then use this to calculate the starting height.